import prisma from "./cardModel.js";

const seedCards = [
  {
    name: "Son Goku",
    color: "red",
    number: "FS01-01",
    type: "Leader",
    image: "http://localhost:3000/images/FS01/FS01-01_b.webp",
  },
  {
    name: "Whis",
    color: "red",
    number: "FS01-02",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-02.webp",
  },
  {
    name: "Master Roshi",
    color: "red",
    number: "FS01-03",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-03.webp",
  },
  {
    name: "Krillin",
    color: "red",
    number: "FS01-04",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-04.webp",
  },
  {
    name: "Shin",
    color: "red",
    number: "FS01-05",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-05.webp",
  },
  {
    name: "Android 17",
    color: "red",
    number: "FS01-06",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-06.webp",
  },
  {
    name: "Android 18",
    color: "red",
    number: "FS01-07",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-07.webp",
  },
  {
    name: "Son Goku",
    color: "red",
    number: "FS01-08",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-08.webp",
  },
  {
    name: "Son Gohan: Adolescence",
    color: "red",
    number: "FS01-09",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-09.webp",
  },
  {
    name: "Tien Shinhan",
    color: "red",
    number: "FS01-10",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-10.webp",
  },
  {
    name: "Piccolo",
    color: "red",
    number: "FS01-11",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-11.webp",
  },
  {
    name: "Beerus",
    color: "red",
    number: "FS01-12",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-12.webp",
  },
  {
    name: "Frieza",
    color: "red",
    number: "FS01-13",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-13.webp",
  },
  {
    name: "Vegeta",
    color: "red",
    number: "FS01-14",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-14.webp",
  },
  {
    name: "Kamehameha",
    color: "red",
    number: "FS01-15",
    type: "Extra",
    image: "http://localhost:3000/images/FS01/FS01-15.webp",
  },
  {
    name: "God Kamehameha",
    color: "red",
    number: "FS01-16",
    type: "Battle",
    image: "http://localhost:3000/images/FS01/FS01-16.webp",
  },
  {
    name: "Vegeta",
    color: "blue",
    number: "FS02-01",
    type: "Leader",
    image: "http://localhost:3000/images/FS02/FS02-01_b.webp",
  },
  {
    name: "Gotenks",
    color: "blue",
    number: "FS02-02",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-02.webp",
  },
  {
    name: "Gotenks",
    color: "blue",
    number: "FS02-03",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-03.webp",
  },
  {
    name: "Son Goku",
    color: "blue",
    number: "FS02-04",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-04.webp",
  },
  {
    name: "Son Goten",
    color: "blue",
    number: "FS02-05",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-05.webp",
  },
  {
    name: "Son Goten",
    color: "blue",
    number: "FS02-06",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-06.webp",
  },
  {
    name: "Son Gohan: Adolescence",
    color: "blue",
    number: "FS02-07",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-07.webp",
  },
  {
    name: "Trunks: Youth",
    color: "blue",
    number: "FS02-08",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-08.webp",
  },
  {
    name: "Trunks: Youth",
    color: "blue",
    number: "FS02-09",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-09.webp",
  },
  {
    name: "Videl",
    color: "blue",
    number: "FS02-10",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-10.webp",
  },
  {
    name: "Piccolo",
    color: "blue",
    number: "FS02-11",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-11.webp",
  },
  {
    name: "Bulma",
    color: "blue",
    number: "FS02-12",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-12.webp",
  },
  {
    name: "Vegeta",
    color: "blue",
    number: "FS02-13",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-13.webp",
  },
  {
    name: "Majin Buu: Good",
    color: "blue",
    number: "FS02-14",
    type: "Battle",
    image: "http://localhost:3000/images/FS02/FS02-14.webp",
  },
  {
    name: "Galick Gun",
    color: "blue",
    number: "FS02-15",
    type: "Extra",
    image: "http://localhost:3000/images/FS02/FS02-15.webp",
  },
  {
    name: "Final Flash",
    color: "blue",
    number: "FS02-16",
    type: "Extra",
    image: "http://localhost:3000/images/FS02/FS02-16.webp",
  },
  {
    name: "Broly",
    color: "green",
    number: "FS03-01",
    type: "Leader",
    image: "http://localhost:3000/images/FS03/FS03-01_b.webp",
  },
  {
    name: "Angol",
    color: "green",
    number: "FS03-02",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-02.webp",
  },
  {
    name: "Shamoian",
    color: "green",
    number: "FS03-03",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-03.webp",
  },
  {
    name: "Turles",
    color: "green",
    number: "FS03-04",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-04.webp",
  },
  {
    name: "Nappa",
    color: "green",
    number: "FS03-05",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-05.webp",
  },
  {
    name: "Paragus",
    color: "green",
    number: "FS03-06",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-06.webp",
  },
  {
    name: "Paragus",
    color: "green",
    number: "FS03-07",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-07.webp",
  },
  {
    name: "Broly",
    color: "green",
    number: "FS03-08",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-08.webp",
  },
  {
    name: "Broly",
    color: "green",
    number: "FS03-09",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-09.webp",
  },
  {
    name: "Broly: BR",
    color: "green",
    number: "FS03-10",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-10.webp",
  },
  {
    name: "Vegeta",
    color: "green",
    number: "FS03-11",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-11.webp",
  },
  {
    name: "King Vegeta",
    color: "green",
    number: "FS03-12",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-12.webp",
  },
  {
    name: "Moah",
    color: "green",
    number: "FS03-13",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-13.webp",
  },
  {
    name: "Raditz",
    color: "green",
    number: "FS03-14",
    type: "Battle",
    image: "http://localhost:3000/images/FS03/FS03-14.webp",
  },
  {
    name: "Gigantic Meteor",
    color: "green",
    number: "FS03-15",
    type: "Extra",
    image: "http://localhost:3000/images/FS03/FS03-15.webp",
  },
  {
    name: "Destructive Strength",
    color: "green",
    number: "FS03-16",
    type: "Extra",
    image: "http://localhost:3000/images/FS03/FS03-16.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FS04-01",
    type: "Leader",
    image: "http://localhost:3000/images/FS04/FS04-01_b.webp",
  },
  {
    name: "Cui",
    color: "yellow",
    number: "FS04-02",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-02.webp",
  },
  {
    name: "Golden Frieza",
    color: "yellow",
    number: "FS04-03",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-03.webp",
  },
  {
    name: "King Cold",
    color: "yellow",
    number: "FS04-04",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-04.webp",
  },
  {
    name: "Zarbon",
    color: "yellow",
    number: "FS04-05",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-05.webp",
  },
  {
    name: "Shisami",
    color: "yellow",
    number: "FS04-06",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-06.webp",
  },
  {
    name: "Sorbet",
    color: "yellow",
    number: "FS04-07",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-07.webp",
  },
  {
    name: "Tagoma",
    color: "yellow",
    number: "FS04-08",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-08.webp",
  },
  {
    name: "Cheelai: BR",
    color: "yellow",
    number: "FS04-09",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-09.webp",
  },
  {
    name: "Dodoria",
    color: "yellow",
    number: "FS04-10",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-10.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FS04-11",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-11.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FS04-12",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-12.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FS04-13",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-13.webp",
  },
  {
    name: "Lemo: BR",
    color: "yellow",
    number: "FS04-14",
    type: "Battle",
    image: "http://localhost:3000/images/FS04/FS04-14.webp",
  },
  {
    name: "Golden Death Beam",
    color: "yellow",
    number: "FS04-15",
    type: "Extra",
    image: "http://localhost:3000/images/FS04/FS04-15.webp",
  },
  {
    name: "Death Ball",
    color: "yellow",
    number: "FS04-16",
    type: "Extra",
    image: "http://localhost:3000/images/FS04/FS04-16.webp",
  },
  {
    name: "Son Goku",
    color: "red",
    number: "FB01-001",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-001_b.webp",
  },
  {
    name: "Beerus",
    color: "red",
    number: "FB01-002",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-002_b.webp",
  },
  {
    name: "Vados",
    color: "red",
    number: "FB01-003",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-003.webp",
  },
  {
    name: "Whis",
    color: "red",
    number: "FB01-004",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-004.webp",
  },
  {
    name: "Master Roshi",
    color: "red",
    number: "FB01-005",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-005.webp",
  },
  {
    name: "Caulifla",
    color: "red",
    number: "FB01-006",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-006.webp",
  },
  {
    name: "Cabba",
    color: "red",
    number: "FB01-007",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-007.webp",
  },
  {
    name: "Krillin",
    color: "red",
    number: "FB01-008",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-008.webp",
  },
  {
    name: "Kale",
    color: "red",
    number: "FB01-009",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-009.webp",
  },
  {
    name: "Saonel",
    color: "red",
    number: "FB01-010",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-010.webp",
  },
  {
    name: "Champa",
    color: "red",
    number: "FB01-011",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-011.webp",
  },
  {
    name: "Shin",
    color: "red",
    number: "FB01-012",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-012.webp",
  },
  {
    name: "Android 17",
    color: "red",
    number: "FB01-013",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-013.webp",
  },
  {
    name: "Android 18",
    color: "red",
    number: "FB01-014",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-014.webp",
  },
  {
    name: "Son Goku",
    color: "red",
    number: "FB01-015",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-015.webp",
  },
  {
    name: "Son Gohan: Adolescence",
    color: "red",
    number: "FB01-016",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-016.webp",
  },
  {
    name: "Great Priest",
    color: "red",
    number: "FB01-017",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-017.webp",
  },
  {
    name: "Tien Shinhan",
    color: "red",
    number: "FB01-018",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-018.webp",
  },
  {
    name: "Dr. Rota",
    color: "red",
    number: "FB01-019",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-019.webp",
  },
  {
    name: "Piccolo",
    color: "red",
    number: "FB01-020",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-020.webp",
  },
  {
    name: "Hit",
    color: "red",
    number: "FB01-021",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-021.webp",
  },
  {
    name: "Pirina",
    color: "red",
    number: "FB01-022",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-022.webp",
  },
  {
    name: "Beerus",
    color: "red",
    number: "FB01-023",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-023.webp",
  },
  {
    name: "Frieza",
    color: "red",
    number: "FB01-024",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-024.webp",
  },
  {
    name: "Frost",
    color: "red",
    number: "FB01-025",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-025.webp",
  },
  {
    name: "Fuwa",
    color: "red",
    number: "FB01-026",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-026.webp",
  },
  {
    name: "Vegeta",
    color: "red",
    number: "FB01-027",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-027.webp",
  },
  {
    name: "Botama",
    color: "red",
    number: "FB01-028",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-028.webp",
  },
  {
    name: "Magetta",
    color: "red",
    number: "FB01-029",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-029.webp",
  },
  {
    name: "Strong Warriors of Universe 6",
    color: "red",
    number: "FB01-031",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-031.webp",
  },
  {
    name: "Tournament of Power Arena",
    color: "red",
    number: "FB01-032",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-032.webp",
  },
  {
    name: "Time-Skip",
    color: "red",
    number: "FB01-033",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-033.webp",
  },
  {
    name: "Mafuba",
    color: "red",
    number: "FB01-034",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-034.webp",
  },
  {
    name: "Goku Black",
    color: "blue",
    number: "FB01-035",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-035_b.webp",
  },
  {
    name: "Trunks: Future",
    color: "blue",
    number: "FB01-036",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-036_b.webp",
  },
  {
    name: "Goku Black",
    color: "blue",
    number: "FB01-037",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-037.webp",
  },
  {
    name: "Goku Black",
    color: "blue",
    number: "FB01-038",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-038.webp",
  },
  {
    name: "Goku Black",
    color: "blue",
    number: "FB01-039",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-039.webp",
  },
  {
    name: "Gowasu",
    color: "blue",
    number: "FB01-040",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-040.webp",
  },
  {
    name: "Gowasu",
    color: "blue",
    number: "FB01-041",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-041.webp",
  },
  {
    name: "Yamasu",
    color: "blue",
    number: "FB01-042",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-042.webp",
  },
  {
    name: "Zamasu",
    color: "blue",
    number: "FB01-043",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-043.webp",
  },
  {
    name: "Zamasu",
    color: "blue",
    number: "FB01-044",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-044.webp",
  },
  {
    name: "Shu",
    color: "blue",
    number: "FB01-045",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-045.webp",
  },
  {
    name: "Son Goku",
    color: "blue",
    number: "FB01-046",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-046.webp",
  },
  {
    name: "Son Goku",
    color: "blue",
    number: "FB01-047",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-047.webp",
  },
  {
    name: "Son Goku",
    color: "blue",
    number: "FB01-048",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-048.webp",
  },
  {
    name: "Trunks: Future",
    color: "blue",
    number: "FB01-049",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-049.webp",
  },
  {
    name: "Trunks: Future",
    color: "blue",
    number: "FB01-050",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-050.webp",
  },
  {
    name: "Trunks: Future",
    color: "blue",
    number: "FB01-051",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-051.webp",
  },
  {
    name: "Trunks: Youth",
    color: "blue",
    number: "FB01-052",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-052.webp",
  },
  {
    name: "Babarian",
    color: "blue",
    number: "FB01-053",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-053.webp",
  },
  {
    name: "Haru/Maki",
    color: "blue",
    number: "FB01-054",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-054.webp",
  },
  {
    name: "Pan",
    color: "blue",
    number: "FB01-055",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-055.webp",
  },
  {
    name: "Pilaf",
    color: "blue",
    number: "FB01-056",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-056.webp",
  },
  {
    name: "Bulma",
    color: "blue",
    number: "FB01-057",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-057.webp",
  },
  {
    name: "Vegeta",
    color: "blue",
    number: "FB01-058",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-058.webp",
  },
  {
    name: "Vegeta",
    color: "blue",
    number: "FB01-059",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-059.webp",
  },
  {
    name: "Vegeta",
    color: "blue",
    number: "FB01-060",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-060.webp",
  },
  {
    name: "Mai: Future",
    color: "blue",
    number: "FB01-061",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-061.webp",
  },
  {
    name: "Mai: Future",
    color: "blue",
    number: "FB01-062",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-062.webp",
  },
  {
    name: "Yajirobe: Future",
    color: "blue",
    number: "FB01-063",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-063.webp",
  },
  {
    name: "Blade of Despair",
    color: "blue",
    number: "FB01-064",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-064.webp",
  },
  {
    name: "Time Machine",
    color: "blue",
    number: "FB01-065",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-065.webp",
  },
  {
    name: "Final Hope Slash",
    color: "blue",
    number: "FB01-066",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-066.webp",
  },
  {
    name: "Black Kamehameha",
    color: "blue",
    number: "FB01-067",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-067.webp",
  },
  {
    name: "Sinister Sickle",
    color: "blue",
    number: "FB01-068",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-068.webp",
  },
  {
    name: "Sinister Shadows",
    color: "blue",
    number: "FB01-069",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-069.webp",
  },
  {
    name: "Android 17",
    color: "green",
    number: "FB01-070",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-070_b.webp",
  },
  {
    name: "Son Gohan: Childhood",
    color: "green",
    number: "FB01-071",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-071_b.webp",
  },
  {
    name: "Krillin",
    color: "green",
    number: "FB01-072",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-072.webp",
  },
  {
    name: "Android 16",
    color: "green",
    number: "FB01-073",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-073.webp",
  },
  {
    name: "Android 16",
    color: "green",
    number: "FB01-074",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-074.webp",
  },
  {
    name: "Android 17",
    color: "green",
    number: "FB01-075",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-075.webp",
  },
  {
    name: "Android 17",
    color: "green",
    number: "FB01-076",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-076.webp",
  },
  {
    name: "Android 17",
    color: "green",
    number: "FB01-077",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-077.webp",
  },
  {
    name: "Android 17/Android 18",
    color: "green",
    number: "FB01-078",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-078.webp",
  },
  {
    name: "Android 18",
    color: "green",
    number: "FB01-079",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-079.webp",
  },
  {
    name: "Android 18",
    color: "green",
    number: "FB01-080",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-080.webp",
  },
  {
    name: "Android 18",
    color: "green",
    number: "FB01-081",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-081.webp",
  },
  {
    name: "Android 19",
    color: "green",
    number: "FB01-082",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-082.webp",
  },
  {
    name: "Android 20",
    color: "green",
    number: "FB01-083",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-083.webp",
  },
  {
    name: "Android 20",
    color: "green",
    number: "FB01-084",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-084.webp",
  },
  {
    name: "Son Goku",
    color: "green",
    number: "FB01-085",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-085.webp",
  },
  {
    name: "Son Goku",
    color: "green",
    number: "FB01-086",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-086.webp",
  },
  {
    name: "Son Goku",
    color: "green",
    number: "FB01-087",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-087.webp",
  },
  {
    name: "Son Gohan: Childhood",
    color: "green",
    number: "FB01-088",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-088.webp",
  },
  {
    name: "Son Gohan: Childhood",
    color: "green",
    number: "FB01-089",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-089.webp",
  },
  {
    name: "Son Gohan",
    color: "green",
    number: "FB01-090",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-090.webp",
  },
  {
    name: "Tien Shinhan",
    color: "green",
    number: "FB01-091",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-091.webp",
  },
  {
    name: "Trunks: Future",
    color: "green",
    number: "FB01-092",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-092.webp",
  },
  {
    name: "Trunks: Future",
    color: "green",
    number: "FB01-093",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-093.webp",
  },
  {
    name: "Piccolo",
    color: "green",
    number: "FB01-094",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-094.webp",
  },
  {
    name: "Vegeta",
    color: "green",
    number: "FB01-095",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-095.webp",
  },
  {
    name: "Vegeta",
    color: "green",
    number: "FB01-096",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-096.webp",
  },
  {
    name: "Hercule",
    color: "green",
    number: "FB01-097",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-097.webp",
  },
  {
    name: "Yamcha",
    color: "green",
    number: "FB01-098",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-098.webp",
  },
  {
    name: "Eye Beam",
    color: "green",
    number: "FB01-099",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-099.webp",
  },
  {
    name: "Brother-Sister Combination",
    color: "green",
    number: "FB01-100",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-100.webp",
  },
  {
    name: "Instant Kamehameha",
    color: "green",
    number: "FB01-101",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-101.webp",
  },
  {
    name: "Dr. Gero's Lab",
    color: "green",
    number: "FB01-102",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-102.webp",
  },
  {
    name: "Big Bang Attack",
    color: "green",
    number: "FB01-103",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-103.webp",
  },
  {
    name: "Ginyu",
    color: "yellow",
    number: "FB01-104",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-104_b.webp",
  },
  {
    name: "Cooler",
    color: "yellow",
    number: "FB01-105",
    type: "Leader",
    image: "http://localhost:3000/images/FB01/FB01-105_b.webp",
  },
  {
    name: "Appule",
    color: "yellow",
    number: "FB01-106",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-106.webp",
  },
  {
    name: "Ginyu",
    color: "yellow",
    number: "FB01-107",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-107.webp",
  },
  {
    name: "Ginyu",
    color: "yellow",
    number: "FB01-108",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-108.webp",
  },
  {
    name: "Ginyu",
    color: "yellow",
    number: "FB01-109",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-109.webp",
  },
  {
    name: "Ginyu",
    color: "yellow",
    number: "FB01-110",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-110.webp",
  },
  {
    name: "Cui",
    color: "yellow",
    number: "FB01-111",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-111.webp",
  },
  {
    name: "Cooler",
    color: "yellow",
    number: "FB01-112",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-112.webp",
  },
  {
    name: "Cooler",
    color: "yellow",
    number: "FB01-113",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-113.webp",
  },
  {
    name: "Guldo",
    color: "yellow",
    number: "FB01-114",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-114.webp",
  },
  {
    name: "King Cold",
    color: "yellow",
    number: "FB01-115",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-115.webp",
  },
  {
    name: "Zarbon",
    color: "yellow",
    number: "FB01-116",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-116.webp",
  },
  {
    name: "Salza",
    color: "yellow",
    number: "FB01-117",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-117.webp",
  },
  {
    name: "Salza",
    color: "yellow",
    number: "FB01-118",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-118.webp",
  },
  {
    name: "Jeice",
    color: "yellow",
    number: "FB01-119",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-119.webp",
  },
  {
    name: "Sui",
    color: "yellow",
    number: "FB01-120",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-120.webp",
  },
  {
    name: "Chilled",
    color: "yellow",
    number: "FB01-121",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-121.webp",
  },
  {
    name: "Core",
    color: "yellow",
    number: "FB01-122",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-122.webp",
  },
  {
    name: "Dodoria",
    color: "yellow",
    number: "FB01-123",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-123.webp",
  },
  {
    name: "Neiz",
    color: "yellow",
    number: "FB01-124",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-124.webp",
  },
  {
    name: "Nail",
    color: "yellow",
    number: "FB01-125",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-125.webp",
  },
  {
    name: "Burter",
    color: "yellow",
    number: "FB01-126",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-126.webp",
  },
  {
    name: "Banan",
    color: "yellow",
    number: "FB01-127",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-127.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FB01-128",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-128.webp",
  },
  {
    name: "Frieza",
    color: "yellow",
    number: "FB01-129",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-129.webp",
  },
  {
    name: "Mecha Frieza",
    color: "yellow",
    number: "FB01-130",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-130.webp",
  },
  {
    name: "Meta-Cooler",
    color: "yellow",
    number: "FB01-131",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-131.webp",
  },
  {
    name: "Recoome",
    color: "yellow",
    number: "FB01-132",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-132.webp",
  },
  {
    name: "Bonds of the Ginyu Force",
    color: "yellow",
    number: "FB01-133",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-133.webp",
  },
  {
    name: "We Are Cooler's Armored Squadron!",
    color: "yellow",
    number: "FB01-134",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-134.webp",
  },
  {
    name: "Crusher Ball",
    color: "yellow",
    number: "FB01-135",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-135.webp",
  },
  {
    name: "Supernova",
    color: "yellow",
    number: "FB01-136",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-136.webp",
  },
  {
    name: "Body Change",
    color: "yellow",
    number: "FB01-137",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-136.webp",
  },
  {
    name: "Now You See The Power of the Ginyu Force!",
    color: "yellow",
    number: "FB01-138",
    type: "Extra",
    image: "http://localhost:3000/images/FB01/FB01-138.webp",
  },
  {
    name: "Son Goku",
    color: "red",
    number: "FB01-139",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-139.webp",
  },
  {
    name: "Son Gohan: Childhood",
    color: "green",
    number: "FB01-140",
    type: "Battle",
    image: "http://localhost:3000/images/FB01/FB01-140.webp",
  },
];

async function seedDatabase() {
  await prisma.card.createMany({
    data: seedCards,
  });
}

async function main() {
  try {
    console.log("seeding Database...");
    await seedDatabase();
    console.log("seeding completed successfully!");
  } catch (error) {
    console.error(error);
  } finally {
    await prisma.$disconnect();
  }
}

main();


/**
 *  Example Starter Deck List
 * [
    {
        "id": 338,
        "name": "Son Goku",
        "color": "red",
        "number": "FS01-01",
        "type": "Leader",
        "image": "http://localhost:3000/images/FS01/FS01-01_b.webp"
    },
    {
        "id": 339,
        "name": "Whis",
        "color": "red",
        "number": "FS01-02",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-02.webp"
    },
    {
        "id": 339,
        "name": "Whis",
        "color": "red",
        "number": "FS01-02",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-02.webp"
    },
    {
        "id": 339,
        "name": "Whis",
        "color": "red",
        "number": "FS01-02",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-02.webp"
    },
    {
        "id": 339,
        "name": "Whis",
        "color": "red",
        "number": "FS01-02",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-02.webp"
    },
    {
        "id": 340,
        "name": "Master Roshi",
        "color": "red",
        "number": "FS01-03",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-03.webp"
    },
    {
        "id": 340,
        "name": "Master Roshi",
        "color": "red",
        "number": "FS01-03",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-03.webp"
    },
    {
        "id": 340,
        "name": "Master Roshi",
        "color": "red",
        "number": "FS01-03",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-03.webp"
    },
    {
        "id": 340,
        "name": "Master Roshi",
        "color": "red",
        "number": "FS01-03",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-03.webp"
    },
    {
        "id": 341,
        "name": "Krillin",
        "color": "red",
        "number": "FS01-04",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-04.webp"
    },
    {
        "id": 341,
        "name": "Krillin",
        "color": "red",
        "number": "FS01-04",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-04.webp"
    },
    {
        "id": 342,
        "name": "Shin",
        "color": "red",
        "number": "FS01-05",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-05.webp"
    },
    {
        "id": 342,
        "name": "Shin",
        "color": "red",
        "number": "FS01-05",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-05.webp"
    },
    {
        "id": 342,
        "name": "Shin",
        "color": "red",
        "number": "FS01-05",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-05.webp"
    },
    {
        "id": 342,
        "name": "Shin",
        "color": "red",
        "number": "FS01-05",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-05.webp"
    },
    {
        "id": 343,
        "name": "Android 17",
        "color": "red",
        "number": "FS01-06",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-06.webp"
    },
    {
        "id": 343,
        "name": "Android 17",
        "color": "red",
        "number": "FS01-06",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-06.webp"
    },
    {
        "id": 343,
        "name": "Android 17",
        "color": "red",
        "number": "FS01-06",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-06.webp"
    },
    {
        "id": 343,
        "name": "Android 17",
        "color": "red",
        "number": "FS01-06",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-06.webp"
    },
    {
        "id": 344,
        "name": "Android 18",
        "color": "red",
        "number": "FS01-07",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-07.webp"
    },
    {
        "id": 344,
        "name": "Android 18",
        "color": "red",
        "number": "FS01-07",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-07.webp"
    },
    {
        "id": 344,
        "name": "Android 18",
        "color": "red",
        "number": "FS01-07",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-07.webp"
    },
    {
        "id": 344,
        "name": "Android 18",
        "color": "red",
        "number": "FS01-07",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-07.webp"
    },
    {
        "id": 345,
        "name": "Son Goku",
        "color": "red",
        "number": "FS01-08",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-08.webp"
    },
    {
        "id": 345,
        "name": "Son Goku",
        "color": "red",
        "number": "FS01-08",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-08.webp"
    },
    {
        "id": 346,
        "name": "Son Gohan: Adolescence",
        "color": "red",
        "number": "FS01-09",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-09.webp"
    },
    {
        "id": 346,
        "name": "Son Gohan: Adolescence",
        "color": "red",
        "number": "FS01-09",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-09.webp"
    },
    {
        "id": 347,
        "name": "Tien Shinhan",
        "color": "red",
        "number": "FS01-10",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-10.webp"
    },
    {
        "id": 347,
        "name": "Tien Shinhan",
        "color": "red",
        "number": "FS01-10",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-10.webp"
    },
    {
        "id": 347,
        "name": "Tien Shinhan",
        "color": "red",
        "number": "FS01-10",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-10.webp"
    },
    {
        "id": 347,
        "name": "Tien Shinhan",
        "color": "red",
        "number": "FS01-10",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-10.webp"
    },
    {
        "id": 348,
        "name": "Piccolo",
        "color": "red",
        "number": "FS01-11",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-11.webp"
    },
    {
        "id": 348,
        "name": "Piccolo",
        "color": "red",
        "number": "FS01-11",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-11.webp"
    },
    {
        "id": 348,
        "name": "Piccolo",
        "color": "red",
        "number": "FS01-11",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-11.webp"
    },
    {
        "id": 348,
        "name": "Piccolo",
        "color": "red",
        "number": "FS01-11",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-11.webp"
    },
    {
        "id": 349,
        "name": "Beerus",
        "color": "red",
        "number": "FS01-12",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-12.webp"
    },
    {
        "id": 349,
        "name": "Beerus",
        "color": "red",
        "number": "FS01-12",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-12.webp"
    },
    {
        "id": 350,
        "name": "Frieza",
        "color": "red",
        "number": "FS01-13",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-13.webp"
    },
    {
        "id": 350,
        "name": "Frieza",
        "color": "red",
        "number": "FS01-13",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-13.webp"
    },
    {
        "id": 350,
        "name": "Frieza",
        "color": "red",
        "number": "FS01-13",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-13.webp"
    },
    {
        "id": 350,
        "name": "Frieza",
        "color": "red",
        "number": "FS01-13",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-13.webp"
    },
    {
        "id": 351,
        "name": "Vegeta",
        "color": "red",
        "number": "FS01-14",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-14.webp"
    },
    {
        "id": 351,
        "name": "Vegeta",
        "color": "red",
        "number": "FS01-14",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-14.webp"
    },
    {
        "id": 351,
        "name": "Vegeta",
        "color": "red",
        "number": "FS01-14",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-14.webp"
    },
    {
        "id": 351,
        "name": "Vegeta",
        "color": "red",
        "number": "FS01-14",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-14.webp"
    },
    {
        "id": 352,
        "name": "Kamehameha",
        "color": "red",
        "number": "FS01-15",
        "type": "Extra",
        "image": "http://localhost:3000/images/FS01/FS01-15.webp"
    },
    {
        "id": 352,
        "name": "Kamehameha",
        "color": "red",
        "number": "FS01-15",
        "type": "Extra",
        "image": "http://localhost:3000/images/FS01/FS01-15.webp"
    },
    {
        "id": 353,
        "name": "God Kamehameha",
        "color": "red",
        "number": "FS01-16",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-16.webp"
    },
    {
        "id": 353,
        "name": "God Kamehameha",
        "color": "red",
        "number": "FS01-16",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-16.webp"
    },
    {
        "id": 353,
        "name": "God Kamehameha",
        "color": "red",
        "number": "FS01-16",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-16.webp"
    },
    {
        "id": 353,
        "name": "God Kamehameha",
        "color": "red",
        "number": "FS01-16",
        "type": "Battle",
        "image": "http://localhost:3000/images/FS01/FS01-16.webp"
    }
]
 */
